### ISSUE TITLE
Yaf

### ISSUE THREAD

**Issue by adulau** [caesar0301/awesome-pcaptools#17]
Yaf is missing. It's a reliable piece of software, quite solid and able to generate flow records from pcap. This is very nice for indexing huge pcap or even doing packet capture. The recent version can even extract payloads and put in the Flow records.

https://tools.netsa.cert.org/yaf/yaf.html

Thank you for your work.

**Comment by caesar0301** [comment]
Nice and brief comment. I will replace the original intro with it. :+1:
