### ISSUE TITLE
pcap tcp flow isolation

### ISSUE THREAD

**Issue by cherusk** [caesar0301/awesome-pcaptools#50]
> . I have make the attempt to use made-ready tools like tcpflows, tcpslice, tcpsplit, but all these tools try to either decrease the trace volume (under requirement) or resemble the packets into flow payloads (over requirement). I have not found a simple tool to classify the packets into flows without further processing.

On verge of being invalidate by PR:
https://github.com/simsong/tcpflow/pull/200

**Comment by cherusk** [comment]
Uncertain how to ideally reflect, pushing to you ... :)

**Comment by scribbles** [comment]
Linked PR is related to an external code issue and not relevant to this project. Closing.
