### ISSUE TITLE
A tool for graph visualisation from PCAP

### ISSUE THREAD

**Issue by tbarbette** [caesar0301/awesome-pcaptools#51]
Hi !

Thanks for this database.  But it's still not clear to me which tool could give me a plot of the bandwidth used over time. I think pinpointing tools that can do that would be useful.

Thanks,

Tom

**Comment by scribbles** [comment]
Hi @tbarbette ,

[LibreNMS ](https://www.librenms.org/ )provides visualization functionality. MSFT has a decent article on this topic [here](https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-using-open-source-tools).  Common solutions are combinations of multiple tools. 

Hopefully this helps!
