### ISSUE TITLE
How to determine throughput/bandwidth from a capture

### ISSUE THREAD

**Issue by Laurauma** [caesar0301/awesome-pcaptools#54]
I need to determine the throughput available between TCP client/server based on a capture.

I would be very grateful if someone would indicate a script or tool that allows me to extract the troughput / network bandwidth from a capture pcap file and save it in a csv, txt ...

Any help will be really appreciated
Laura

**Comment by ioload** [comment]
> I need to determine the throughput available between TCP client/server based on a capture.
> 
> I would be very grateful if someone would indicate a script or tool that allows me to extract the troughput / network bandwidth from a capture pcap file and save it in a csv, txt ...
> 
> Any help will be really appreciated
> Laura

Hi Laura, 

Sorry no one answered your question. You can do this in Wireshark by loading pcaps > Statistics > Filter the traffic > I/O Graphs then navigate to the rectangular box at the lower half of the I/O Graphs page then double-click on Filtered Packets and change the Y-Axis from Packets to Bits. Then high Save As at the bottom-right corner and it will give you the option to save it as a .csv. 

Not sure if you will see this, but maybe this could be useful to someone out there!

Cheers!
