### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by arthurvr** [caesar0301/awesome-pcaptools#8]
This repo seems to miss a license. You could use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by scribbles** [comment]
@caesar0301 Any objections to converting to a CC0 license? Recommendations from awesome [here](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md).

**Comment by scribbles** [comment]
License changed to CC0 to align with awesome guidelines.
